USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS MEDALLION_WH 
WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND=60 
AUTO_RESUME=TRUE;
USE WAREHOUSE MEDALLION_WH;
CREATE DATABASE MEDALLION_DB;
CREATE SCHEMA MEDALLION_DB.BRONZE_LAYER;
CREATE SCHEMA MEDALLION_DB.SILVER_LAYER;
CREATE SCHEMA MEDALLION_DB.GOLD_LAYER;

