USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MEDALLION_WH;
USE DATABASE MEDALLION_DB;
USE SCHEMA MEDALLION_DB.BRONZE_LAYER;
CREATE FILE FORMAT IF NOT EXISTS MY_CSV TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER = 1;
CREATE OR REPLACE STAGE RAW_INTERNAL_STAGE FILE_FORMAT = MY_CSV;
