USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MEDALLION_WH;
USE DATABASE MEDALLION_DB;
USE SCHEMA MEDALLION_DB.SILVER_LAYER;

CREATE OR REPLACE TABLE SILVER_CUSTOMERS AS
SELECT
    TRY_TO_NUMBER(CUSTOMER_ID) AS CUSTOMER_ID,
    CUSTOMER_NAME,
    EMAIL,
    REGION,
    CASE WHEN TRY_TO_NUMBER(CUSTOMER_ID) IS NULL OR LENGTH(CUSTOMER_ID) != 3 THEN 'INVALID' ELSE 'VALID' END AS CUSTOMER_ID_STATUS,
    CASE WHEN EMAIL IS NOT NULL AND (CONTAINS(EMAIL,'@email.com') OR CONTAINS(EMAIL,'@gmail.com') OR CONTAINS(EMAIL,'@example.com'))  THEN 'VALID' ELSE 'INVALID' END AS CUSTOMER_EMAIL_STATUS
FROM BRONZE_LAYER.RAW_CUSTOMERS;

CREATE OR REPLACE TABLE SILVER_PRODUCTS AS
SELECT
    TRY_TO_NUMBER(PRODUCT_ID) AS PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    CASE WHEN TRY_TO_NUMBER(PRODUCT_ID) IS NULL OR LENGTH(PRODUCT_ID) != 3 THEN 'INVALID' ELSE 'VALID' END AS PRODUCT_ID_STATUS
FROM BRONZE_LAYER.RAW_PRODUCTS;

CREATE OR REPLACE TABLE SILVER_SALES AS
SELECT
    SALE_ID,
    SALE_DATE,
    TRY_TO_NUMBER(CUSTOMER_ID) AS CUSTOMER_ID,
    TRY_TO_NUMBER(PRODUCT_ID) AS PRODUCT_ID,
    AMOUNT,
    CASE WHEN TRY_TO_NUMBER(SALE_ID) IS NULL OR LENGTH(SALE_ID) >= 5 THEN 'INVALID' ELSE 'VALID' END AS SALE_ID_STATUS,
FROM BRONZE_LAYER.RAW_SALES;

