USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MEDALLION_WH;
USE DATABASE MEDALLION_DB;
USE SCHEMA MEDALLION_DB.SILVER_LAYER;


-- create stream from each entites for CDC purpose
CREATE OR REPLACE STREAM STG_CUSTOMERS ON TABLE BRONZE_LAYER.RAW_CUSTOMERS;
CREATE OR REPLACE STREAM STG_PRODUCTS ON TABLE BRONZE_LAYER.RAW_PRODUCTS;
CREATE OR REPLACE STREAM STG_SALES ON TABLE BRONZE_LAYER.RAW_SALES;



-- create task to do push stream runs


CREATE OR REPLACE TASK TASK_LOAD_SILVER_CUSTOMER
WAREHOUSE = MEDALLION_WH
SCHEDULE = '1 MINUTE'
AS
MERGE INTO SILVER_CUSTOMERS T
USING (SELECT * FROM STG_CUSTOMERS) S
ON T.CUSTOMER_ID = TRY_TO_NUMBER(S.CUSTOMER_ID)
WHEN MATCHED THEN UPDATE SET T.CUSTOMER_NAME = S.CUSTOMER_NAME, T.EMAIL = S.EMAIL , T.REGION = S.REGION
WHEN NOT MATCHED THEN INSERT VALUES (TRY_TO_NUMBER(S.CUSTOMER_ID), S.CUSTOMER_NAME, S.EMAIL, S.REGION,
    CASE WHEN TRY_TO_NUMBER(S.CUSTOMER_ID) IS NULL OR LENGTH(S.CUSTOMER_ID)!=3 THEN 'INVALID' ELSE 'VALID' END,
    CASE WHEN EMAIL IS NOT NULL AND (CONTAINS(EMAIL,'@email.com') OR CONTAINS(EMAIL,'@gmail.com') OR CONTAINS(EMAIL,'@example.com'))  THEN 'VALID' ELSE 'INVALID' END);
ALTER TASK TASK_LOAD_SILVER_CUSTOMER RESUME;

CREATE OR REPLACE TASK TASK_LOAD_SILVER_PRODUCTS
WAREHOUSE = MEDALLION_WH
SCHEDULE = '1 MINUTE'
AS
MERGE INTO SILVER_PRODUCTS 
USING (SELECT * FROM STG_PRODUCTS) S
ON T.PRODUCT_ID = TRY_TO_NUMBER(S.PRODUCT_ID)
WHEN MATCHED THEN UPDATE SET T.PRODUCT_NAME = S.PRODUCT_NAME  , T.CATEGORY = S.CATEGORY 
WHEN NOT MATCHED THEN INSERT VALUES (TRY_TO_NUMBER(S.PRODUCT_ID), S.PRODUCT_NAME, S.CATEGORY,
CASE WHEN TRY_TO_NUMBER(PRODUCT_ID) IS NULL OR LENGTH(PRODUCT_ID) != 3 THEN 'INVALID' ELSE 'VALID' END);
ALTER TASK TASK_LOAD_SILVER_PRODUCTS RESUME;

    
CREATE OR REPLACE TASK TASK_LOAD_SILVER_SALES
WAREHOUSE = MEDALLION_WH
SCHEDULE = '1 MINUTE'
AS
MERGE INTO SILVER_SALES 
USING (SELECT * FROM STG_SALES) S
ON T.SALE_ID = TRY_TO_NUMBER(S.SALE_ID)
WHEN MATCHED THEN UPDATE SET T.CUSTOMER_ID = S.CUSTOMER_ID,T.SALE_DATE = S.SALE_DATE,T.PRODUCT_ID = S.PRODUCT_ID,T.AMOUNT = S.AMOUNT
WHEN NOT MATCHED THEN INSERT VALUES (TRY_TO_NUMBER(S.SALE_ID), S.SALE_DATE, S.CUSTOMER_ID, S.PRODUCT_ID, S.AMOUNT,
CASE WHEN TRY_TO_NUMBER(SALE_ID) IS NULL OR LENGTH(SALE_ID) >= 5 THEN 'INVALID' ELSE 'VALID' END);
ALTER TASK TASK_LOAD_SILVER_SALES RESUME;

