USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MEDALLION_WH;
USE DATABASE MEDALLION_DB;
USE SCHEMA MEDALLION_DB.GOLD_LAYER;

CREATE OR REPLACE DYNAMIC TABLE GOLD_SALES_SUMMARY
TARGET_LAG = '1 MINUTE'
WAREHOUSE = MEDALLION_WH
AS
SELECT
    S.SALE_DATE,
    P.CATEGORY,
    C.REGION,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    SUM(S.AMOUNT) AS TOTAL_AMOUNT
FROM SILVER_LAYER.SILVER_SALES S
JOIN SILVER_LAYER.SILVER_CUSTOMERS C ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN SILVER_LAYER.SILVER_PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 1,2,3;


