USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MEDALLION_WH;
USE DATABASE MEDALLION_DB;
CREATE SCHEMA MEDALLION_DB.DQ_LAYER ;
USE SCHEMA MEDALLION_DB.DQ_LAYER;

CREATE OR REPLACE FUNCTION DMF_CHECK_SILVER_SALES()
RETURNS TABLE (
    METRIC VARCHAR,
    VALUE NUMBER
)
AS
$$
SELECT 'NULL_CUSTOMER_ID' AS METRIC, COUNT(*) AS VALUE 
FROM SILVER_LAYER.SILVER_SALES WHERE CUSTOMER_ID IS NULL
UNION ALL
SELECT 'INCOMPLETED_SALES_ID', COUNT(*) FROM SILVER_LAYER.SILVER_SALES WHERE SALE_ID_STATUS ='INVALID'
UNION ALL
SELECT 'INVALID_CUSTOMER_ID', COUNT(*) 
FROM SILVER_LAYER.SILVER_CUSTOMERS WHERE CUSTOMER_ID_STATUS='INVALID'
UNION ALL
SELECT 'COMPLETED_CUSTOMER_ID', COUNT(*) 
FROM SILVER_LAYER.SILVER_CUSTOMERS WHERE CUSTOMER_ID_STATUS='VALID'
UNION ALL
SELECT 'INVALID_CUSTOMER_EMAIL', COUNT(*) 
FROM SILVER_LAYER.SILVER_CUSTOMERS WHERE CUSTOMER_EMAIL_STATUS='INVALID'
UNION ALL
SELECT 'INVALID_PRODUCT_ID', COUNT(*) 
FROM SILVER_LAYER.SILVER_PRODUCTS WHERE PRODUCT_ID_STATUS='INVALID'
$$;


SELECT * FROM TABLE(DMF_CHECK_SILVER_SALES());
