USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MEDALLION_WH;
USE DATABASE MEDALLION_DB;
USE SCHEMA MEDALLION_DB.DQ_LAYER;

-- Create masking policy
CREATE OR REPLACE MASKING POLICY EMAIL_MASK_POLICY
AS (VAL STRING) RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ADMIN','ANALYST') THEN VAL
    ELSE REGEXP_REPLACE(VAL,'.*@','XXXX@')
END;



-- APPLY MASKING POLICY 

ALTER TABLE SILVER_LAYER.SILVER_CUSTOMERS
MODIFY COLUMN EMAIL
SET MASKING POLICY EMAIL_MASK_POLICY;
